config/routes.rb
SacPage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root :to => "pages#home"

  post '/close_race'                                  => 'application#close_race',                   as: :close_race

  get '/noticias'                                     => 'pages#news',                              as: :news
  get '/noticias/:id'                                 => 'pages#notice',                            as: :notice

  get '/categorias'                                   => 'pages#categories',                        as: :categories
  get '/categorias/:id'                               => 'categories#show',                         as: :category
  get '/categorias/:id/campeonatos'                   => 'categories#show_championships',           as: :category_championships

  get '/categorias/:category_id/circuitos'            => 'circuits#index',                          as: :circuits
  get '/categorias/:category_id/circuitos/:id'        => 'circuits#show',                           as: :show_circuit

  get '/categorias/:category_id/pilotos'              => 'categories#show_pilots',                  as: :category_pilots
  get '/categorias/:category_id/pilotos/:id'          => 'categories#pilot',                        as: :pilot

  get '/categorias/:category_id/galerias'             => 'categories#show_gallery',                 as: :category_gallery
  get '/categorias/:category_id/galerias/:id'         => 'categories#show_albun',                   as: :category_gallery_albun

  get '/categorias/:id/reglamentos'                   => 'categories#show_regulation',              as: :category_regulation

  get '/categorias/:category_id/calendario'           => 'categories#show_calendar',                as: :category_calendar
  get '/categorias/:category_id/calendario/fecha/:id' => 'categories#race',                         as: :race

  get '/galeria'                                      => 'pages#galleries',                         as: :galleries
  get '/albun/:id'                                    => 'pages#albun',                             as: :albun

  get '/nosotros'                                     => 'pages#about',                             as: :about

  get '/contacto'                                     => 'pages#contact',                           as: :contact
  post 'send_contact_info'                            => 'pages#send_contact_info',                 as: :send_contact_info

  get "/championship_by_year"                         => 'categories#championship_by_year',         as: :championship_by_year
  get "/championship_query"                           => 'categories#championship_query',           as: :championship_query

end

app/views/pages/about.html.erb
<div class="about-page">

	<div class="page-title">
		<h1>Salto Automovil Club</h1>
	</div>

	<div class="description-sac">
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p>
		<%= link_to("#", class: "fb-share-btn", :"data-name" => "Salto Automovil Club", :"data-caption" => "Institucional", :"data-link" => request.original_url, :"data-picture" => asset_url("logo.png"), :"data-description" => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only fntaining Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum...." ) do %>
      <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
    <% end -%>
	</div>

	<div class="directive">
    <div class="tit-1">
      <h3>Directiva</h3>
    </div>
    <ul class="directive-list">
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Presidente</h3>
					<h5>Sr. Carlos Lura  </h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Vicepresidente</h3>
					<h5>Sr. Teo Kazachuk  </h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Secretario</h3>
					<h5>Sr. Guillermo Barbat  </h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Tesorero</h3>
					<h5>Sr. Virgilio Favianes  </h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Protesorero</h3>
					<h5>Sr. José María Ubici</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Prosecretario</h3>
					<h5>Sr. Roberto Barbat  </h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Vocal</h3>
					<h5>Sr. Raúl Omar Bottino</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Vocal</h3>
					<h5>Sr. Carlos Bisio</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Vocal</h3>
					<h5>Sr. Bernardo Agustín Zuchi</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Comisión Fiscal</h3>
					<h5>Sr. Lorenzo Martínez</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Comisión Fiscal</h3>
					<h5>Sr. Daniel Machiavello</h5>
				</div>
			</li>
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Comisión Fiscal</h3>
					<h5>Sr. Ezio Menoni</h5>
				</div>
			</li>
  	</ul>
	</div>
	<div class="directive">
    <div class="tit-1">
      <h3>Comision de damas</h3>
    </div>
    <ul class="directive-list">
			<li class="profile-direct">
				<%= image_tag 'default_profile.png' %>
				<div class="text-prof">
					<h3>Presidente</h3>
					<h5>Sr. Carlos Lura  </h5>
				</div>
			</li>

  	</ul>
	</div>
	<br class="clearBoth" />
</div>

<script type="text/javascript">
    $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });
</script>

app/views/pages/albun.html.erb
<div class="categories-pages">
  <br/>
  <div class="albun-wraper">
    <div class="tit-1">
      <h3>FOTOS</h3>
    </div>
    <div class="photo-galery-container">
      <div id="gallery" data-code="<%= @albun.code %>"></div>
    </div>
     <div class="tit-1">
      <h3>VIDEOS</h3>
    </div>
    <div class="video-galery-container">
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $("#gallery").nanoGallery({
      kind: 'flickr',
      userID: '126030921@N08',
      photoset: $('#gallery').data('code'),
      thumbnailWidth: 125,
      thumbnailHeight: 125,
      thumbnailGutterWidth: 20,
      thumbnailGutterHeight: 20,
      thumbnailLabel: { display: false }
    });
  });
</script>

app/views/pages/categories.html.erb
<div class="category-page">
	<div class="page-title">
	 	<h1>Categorias</h1>
  </div>
	<div class="categories-desc">
    <p>
      Actualemnte el club cuenta con 3 categorias y dos subcategorias. Turismo Pista SAC como categoría principal, luego la categoria Fórmula SAC subdividida en "A" y "Super A" y por último la categoria de Kart 125cc subdividida en "A" y Super A".
    </p>
  </div>
  <div class="acces-categ">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
        <div class="category-panel <%= "#{category.short_name}-color"%>" >
          <%= image_tag category.logo %>
        </div>
      <% end -%>
    <% end -%>
  </div>
  <br class="clearBoth" />
</div>

<style type="text/css">
  .category-panel.TPS-color {
    border: 1px solid #d90000;
    color: #d90000;
  }
  .category-panel.FSAC-color{
    border: 1px solid #ff5c26;
    color: #ff5c26;
  }
  .category-panel.K125-color{
    border: 1px solid #ffbf00;
    color: #ffbf00;
  }

  .category-panel.TPS-color:hover{
    border: 2px solid #d90000;
  }
  .category-panel.FSAC-color:hover{
    border: 2px solid #ff5c26;
  }
  .category-panel.K125-color:hover{
    border: 2px solid #ffbf00;
  }

</style>

app/views/pages/contact.html.erb
<div class="contact-page">
	<div class="page-title">
		<h1>Contacto</h1>
	</div>
	<div class="col-md-8">
		<form class="contact-form" role="form" method="post" action="/send_contact_info" accept-charset="UTF-8">
		  <div class="form-group">
		    <label for="name">Nombre</label>
		    <input type="text" name="name" class="form-control" id="name" placeholder="Ingrese su nombre">
		  </div>
		  <div class="form-group">
	    	<label for="email">Email</label>
	    	<input type="email" name="email" class="form-control" id="email" placeholder="Ingrese su email">
	  	</div>
	  	<div class="form-group">
		    <label for="tel">Teléfono</label>
		    <input type="text" name="tel" class="form-control" id="tel" placeholder="Ingrese su teléfono">
		  </div>
		  <div class="form-group">
		  	<label for="tel">Mensaje</label>
				<textarea class="form-control" name="message" rows="5"></textarea>
		  </div>
		  <button type="submit" data-disable-with="Enviando..." class="btn btn-danger">Enviar</button>
		</form>
	</div>
	<div class="contact-rigth">
		<%= image_tag 'yo_me_sumo.jpg', width: 263 %>
	</div>
	<br class="clearBoth" />
</div>

app/views/pages/galleries.html.erb
<div class="gallery-cont">
  <div class="page-title">
    <h1>Multimedia</h1>
    <%= link_to("#", class: "fb-share-btn galleries-F-btn", :"data-name" => "Galerías multimedia SAC",
                                            :"data-caption" => "",
                                            :"data-link" => request.original_url,
                                            :"data-picture" => asset_url("logo.png"),
                                            :"data-description" => "Todas las fotos y videos de las categorias" ) do %>
      <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
    <% end -%>
  </div>
	<div class="albun-cont">
   <div class="tit-1">
      <h3>ALBUNES</h3>
    </div>
    <ul class="polaroids  small-block-grid-2">
      <% @albuns.each do |albun| %>
        <li>
          <%= link_to albun_path(albun) , title: "#{albun.name} - #{albun.date_albun}" do %>
            <%= image_tag albun.front_pic, title: "#{albun.name} - #{albun.date_albun}" %>
          <% end -%>
        </li>
       <% end -%>
    </ul>
  </div>
  <div class="gent-cont">
    <div class="tit-1">
      <h3>Gentileza</h3>
    </div>
    <div class="images">
      <%= link_to "https://www.facebook.com/fede.gonzalez.737" , title: "H7 Produciones" do %>
        <%= image_tag "/assets/h7.jpg", class: "h7"  %>
      <% end -%>
      <%= link_to "https://www.facebook.com/maria.delossantos.9081" , title: "A Ojo De Leopardo" do %>
        <%= image_tag "/assets/a_ojo_de_leopardo.png", class: "oleo"  %>
      <% end -%>
      <%= link_to "http://www.skypilot.uy/" , title: "Skypilot" do %>
        <%= image_tag "/assets/sky_pilot.png", class: "spilot" %>
      <% end -%>
      <%= link_to "https://www.facebook.com/motoramaoficial" , title: "Motorama" do %>
        <%= image_tag "/assets/motorama.png", class: "motora" %>
      <% end -%>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });
</script>

app/views/pages/home.html.erb
<div class="row">
  <div class="box">
    <div class="col-lg-12 text-center">
       <div id="carousel-example-generic" class="carousel slide">
        <ol class="carousel-indicators hidden-xs">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <% @last_news.each_with_index do |notice, i|%>
            <div class="<%= i == 0 ? 'item active' : 'item' %>" >
              <%= link_to notice_path(notice) do %>
                <%= image_tag notice.photo(:carr), class: "carro-img" %>
                <div class="carousel-caption">
                  <h1><span><%= notice.title %></span></h1>
                  <p><%= truncate(notice.context, length: 200) %></p>
                </div>
              <% end -%>
            </div>
          <% end -%>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="icon-next"></span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/pages/news.html.erb
<div class="news-page">
	<div class="page-title">
		<h1>Noticias</h1>
	</div>
	<% @notices.each_with_index do |notice,i| %>
		<div class="news-panel <%= "left-img" if !i.even? %>">
			<%= image_tag notice.photo(:medium), width: 200 %>
			<%= link_to notice_path(notice) do %>
				<h3><%= notice.title %></h3>
			<% end -%>
			<span><%= l(notice.created_at, :format => :short) %></span>
			<p> <%= truncate(notice.context, length: 544) { link_to "más" , notice_path(notice) } %></p>
		</div>
	<% end -%>
	<div class="apple_pagination">
    <%= will_paginate @notices, :container => false %>
  </div>
</div>

app/views/pages/notice.html.erb
<div class="news-page">
  <div class="breadcrumbs">
    <%= link_to "Noticias", news_path() %> /  <a class="last-it" > <%= @notice.title %> </a>
  </div>
  <%= link_to("#", class: "fb-share-btn notice-F-btn", :"data-name" => @notice.title, :"data-caption" => l(@notice.created_at, :format => :short), :"data-link" => request.original_url, :"data-picture" => asset_url(@notice.photo.url(:medium)), :"data-description" => truncate(@notice.context, length: 544) ) do %>
    <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
  <% end -%>
  <div class="page-title">
   <h1><%= @notice.title %></h1>
  </div>
  <div class="notice-panel">
    <%= image_tag @notice.photo(:original), width: 500 %>
    <span><%= l(@notice.created_at, :format => :short) %></span>
    <p><%= @notice.context %></p>
    <br></br>
  </div>
  <br>
</div>
<script type="text/javascript">
    $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });
</script>