config/routes.rb
SacPage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root :to => "pages#home"

  post '/close_race'                                  => 'application#close_race',                   as: :close_race

  get '/noticias'                                     => 'pages#news',                              as: :news
  get '/noticias/:id'                                 => 'pages#notice',                            as: :notice

  get '/categorias'                                   => 'pages#categories',                        as: :categories
  get '/categorias/:id'                               => 'categories#show',                         as: :category
  get '/categorias/:id/campeonatos'                   => 'categories#show_championships',           as: :category_championships

  get '/categorias/:category_id/circuitos'            => 'circuits#index',                          as: :circuits
  get '/categorias/:category_id/circuitos/:id'        => 'circuits#show',                           as: :show_circuit

  get '/categorias/:category_id/pilotos'              => 'categories#show_pilots',                  as: :category_pilots
  get '/categorias/:category_id/pilotos/:id'          => 'categories#pilot',                        as: :pilot

  get '/categorias/:category_id/galerias'             => 'categories#show_gallery',                 as: :category_gallery
  get '/categorias/:category_id/galerias/:id'         => 'categories#show_albun',                   as: :category_gallery_albun

  get '/categorias/:id/reglamentos'                   => 'categories#show_regulation',              as: :category_regulation

  get '/categorias/:category_id/calendario'           => 'categories#show_calendar',                as: :category_calendar
  get '/categorias/:category_id/calendario/fecha/:id' => 'categories#race',                         as: :race

  get '/galeria'                                      => 'pages#galleries',                         as: :galleries
  get '/albun/:id'                                    => 'pages#albun',                             as: :albun

  get '/nosotros'                                     => 'pages#about',                             as: :about

  get '/contacto'                                     => 'pages#contact',                           as: :contact
  post 'send_contact_info'                            => 'pages#send_contact_info',                 as: :send_contact_info

  get "/championship_by_year"                         => 'categories#championship_by_year',         as: :championship_by_year
  get "/championship_query"                           => 'categories#championship_query',           as: :championship_query

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_and_belongs_to_many :pilots
	has_many :championships
  has_many :circuits
  has_many :albuns

	has_attached_file :logo, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/assets/logo.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  def last_championship
    self.championships.first
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_hover

  def show
    @category = Category.find_by_id(params[:id])
  end

  def show_championships
    @category = Category.find_by_id(params[:id])
    @championship = @category.last_championship
  end

  def championship_query
    if params[:sub_category].blank?
      @championship = Championship.where(year: params[:year], category_id: params[:category_id]).first
    else
      @championship = Championship.where(year: params[:year], category_id: params[:category_id], sub_category: params[:sub_category]).first
    end
    respond_to do |format|
      if request.xhr?
        if params[:type] == "2"
          @races = @championship.races
          format.html { render partial: 'championship_by_race', :layout => false}
        else
          format.html { render partial: 'championship_table', :layout => false}
        end
      else
        format.html
      end
    end
  end

  def championship_by_year
    @championships = Championship.unscoped.where(category_id: params[:category_id]).where.not(one_id: nil).order("year ASC")
    @actual_championship =  Championship.actual_championship(params[:category_id])
    respond_to do |format|
      if request.xhr?
        format.html { render partial: 'champions_year', :layout => false}
      else
        format.html
      end
    end
  end

  def show_gallery
    @category = Category.find_by_id(params[:category_id])
  end

  def show_albun
    @albun = Albun.find(params[:id])
    @category = @albun.category
  end

  def show_pilots
    @category = Category.find_by_id(params[:category_id])
    @pilots = @category.pilots.where(active: true)

    respond_to do |format|
      if request.xhr?
        format.json { render json: @pilots.to_json }
      else
        format.html
      end
    end
  end

  def pilot
    @category = Category.find_by_id(params[:category_id])
    @actual_championship = Championship.actual_championship(params[:category_id])
    @pilot = @category.pilots.find(params[:id])
  end

  def show_regulation
    @category = Category.find_by_id(params[:id])
  end

  def show_calendar
    @category = Category.find_by_id(params[:category_id])
    @actual_championship = Championship.actual_championship(@category.id)
    @races = @actual_championship.races
  end

  def race
    @category = Category.find_by_id(params[:category_id])
    @actual_championship = Championship.actual_championship(@category.id)
    @race = Race.find(params[:id])
  end

  def set_hover
    @hover_menu = CONSTANT_MENU_CATEGORIY_ID
  end


end

app/views/categories/_champions_year.html.erb
<div class="table-responsive generic-tbl championship-tbl <%="#{@actual_championship.category.short_name}-color"%>">
  <!-- tabla tcp -->
  <table class="table campeonato-x-anio" id="table-hidden-content">
    <thead>
      <tr>
        <th style="border-right:1px solid white">Año</th>
        <th>Primero</th>
        <th style="border-right:1px solid white">Auto</th>
        <th>Segundo</th>
        <th style="border-right:1px solid white">Auto</th>
        <th>Tercero</th>
        <th>Auto</th>
      </tr>
    </thead>
    <tbody>
      <% @championships.each_with_index do |ch, i|%>
        <tr>
          <td class="pos"><%= ch.year %></td>
          <td class="piloto first"><%= ch.one %> </td>
          <td class="piloto first" style="border-right:1px solid #ddd"><%= ch.one.car %></td>
          <td class="piloto first"><%= ch.two %></td>
          <td class="piloto first" style="border-right:1px solid #ddd"><%= ch.two.car %></td>
          <td class="piloto first"><%= ch.three %></td>
          <td class="piloto first"><%= ch.three.car %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <a id="back-btn " class="champion-for-year <%="#{@actual_championship.category.short_name}-color"%>" href="/categorias/<%= @actual_championship.category_id %>/campeonatos">
    <strong>Atras</strong>
  </a>
  <br class="clearBoth" />
</div>

app/views/categories/pilot.html.erb
<div class="categories-pages">
  <div class="breadcrumbs">
    <%= link_to "Categorias", categories_path() %> / <%= link_to @category.name ,category_path(@category) %> / <%= link_to "Pilotos", category_pilots_path(@category) %> / <a class="last-it <%="#{@category.short_name}-color"%>"><%= @pilot.full_name %></a>
  </div>
  <%= link_to("#", class: "fb-share-btn one-pilot-F-btn", :"data-name" => @pilot.full_name,
                                          :"data-caption" => "Piloto de la categoria #{@category.name}",
                                          :"data-link" => request.original_url,
                                          :"data-picture" => asset_url(@pilot.complete_pic.url(:medium)),
                                          :"data-description" => "Datos del piloto #{@pilot.full_name} perteneciente a la categoria #{@category.name}") do %>
    <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
  <% end -%>
  <div class="caption <%="#{@category.short_name}-color"%>">
    <h1><span><%= @pilot.full_name %></span></h1>
  </div>
  <div class="driver-profile <%="#{@category.short_name}-color"%>">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
        <figure class="cont-driver">
          <%= image_tag @pilot.complete_pic, style: "disply:block"  %>
        </figure>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="data-block">
              <div class="gral-data">
                <span><%= @pilot.age %> años.</span>
                <%= @pilot.city %>
              </div>
              <div class="tc-data clearfix">
                <span><%= @pilot.number(@category.id) %></span>
                <div class="logo divider">
                  <% if @category.id == 2 %>
                      <img class="lazy" data-original="/assets/karting125_logo.png" src="/assets/karting125_logo.png" style="display: inline;width:50px;">
                    <% else %>
                      <img class="lazy" data-original="/assets/logo_vw.png" src="/assets/logo_vw.png" style="display: inline;width:50px;">
                    <% end %>
                </div>
                <div class="model-car">
                  <span>
                    <% if @category.id == 2 %>
                      <%= "Kart 125cc" %>
                    <% else %>
                      <% if @category.id == 3 %>
                        <%= "Fórmula VW" %>
                      <% else -%>
                        <%= @pilot.car %>
                      <% end -%>
                    <% end %>
                  </span>
                </div>
                <div class="team"><span><%= @pilot.team %></span></div>
              </div>
              <div class="stats-current <%="#{@category.short_name}-color"%>">
                <h3>Campeonato <%= !@actual_championship.year.nil? ? @actual_championship.year : "-" %></h3>
                <ul>
                  <% actual_data = Championship.data_of_pilot_in_championship(@pilot.id, @category.id) %>
                  <li><span>Posición</span><strong><%= actual_data[:pos] %></strong></li>
                  <li><span>Puntos</span><strong><%= actual_data[:score] %></strong></li>
                  <li><span>Asistencias</span><strong><%= actual_data[:assists] %></strong></li>
                  <li><span>Mejor resultado</span><strong><%= actual_data[:best_place] %></strong></li>
                </ul>
              </div><!-- /stats-current -->
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="data-block custom-pad">
              <div class="stats-past <%="#{@category.short_name}-color"%>">
                <div class="hd clearfix">
                  <span>Sus números históricos</span>
                  <%= image_tag @pilot.helmet_pic, style: "disply:block"  %>
                  <div class="debut">
                    Debut <%= @category.name %>:
                    <% fr = @pilot.first_race(@category.id) %>
                    <% unless fr.nil? -%>
                      <span><%= l(fr.date, :format => :long)  %>, <%=  fr.city %></span>
                    <% end -%>
                  </div>
                </div>
                <ul>
                  <li><span>Campeonatos</span><strong><%= @pilot.count_champion(@category.id) %></strong></li>
                  <li><span>Carreras</span><strong><%= @pilot.count_races(@category.id) %></strong></li>
                  <li><span>Podios</span><strong><%= @pilot.podios(@category.id) %></strong></li>
                  <li><span>Victorias</span><strong><%= @pilot.all_win_races(@category.id) %></strong></li>
                  <li><span>Pole position</span><strong><%= @pilot.poles(@category.id) %></strong></li>
                </ul>
              </div><!-- /stats-past -->
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="car-details <%="#{@category.short_name}-color"%>">
      <h3>El auto</h3>
      <div class="wrapper">
        <div class="row">
          <div class="car-img-cont">
            <figure class="auto">
              <% if @pilot.car_pic.file? %>
                <%= image_tag @pilot.car_pic, style: "disply:block"  %>
              <% else %>
                <% c = @pilot.car.split(" ") %>
                <%= image_tag "/assets/#{c.first}-#{c.second}-Default.png", style: "disply:block"  %>
              <% end -%>
            </figure>
          </div>
        </div>
      </div>
    </div><!-- /car-details -->
  </div><!-- /driver-profile -->

</div>

<script type="text/javascript">
    $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });
</script>


<style type="text/css">
  .caption.TPS-color h1 span {
    color: #fff;
    background-color: #d90000;
  }
  .caption.FSAC-color h1  span {
    color: #fff;
    background-color: #ff5c26;
  }
  .caption.K125-color h1  span {
    color: #fff;
    background-color: #ffbf00;
  }

  .driver-profile.TPS-color .tc-data > span{
    background-color: #d90000;
  }
  .driver-profile.FSAC-color .tc-data > span{
    background-color: #ff5c26;
  }
  .driver-profile.K125-color .tc-data > span{
    background-color: #ffbf00;
  }

  .driver-profile.TPS-color .stats-current li > strong{
    color: #d90000;
  }
  .driver-profile.FSAC-color .stats-current li > strong{
    color: #ff5c26;
  }
  .driver-profile.K125-color .stats-current li > strong{
    color: #ffbf00;
  }

  .stats-past.TPS-color .hd .debut{
    color: #d90000;
  }
  .stats-past.FSAC-color .hd .debut{
    color: #ff5c26;
  }
  .stats-past.K125-color .hd .debut{
    color: #ffbf00;
  }

  .car-details.TPS-color h3 {
    background-color: #d90000;
  }
  .car-details.FSAC-color h3 {
    background-color: #ff5c26;
  }
  .car-details.K125-color h3 {
    background-color: #ffbf00;
  }

  .car-details.TPS-color .wrapper {
    border-top: 1px solid #d90000;
  }
  .car-details.FSAC-color .wrapper {
    border-top: 1px solid #ff5c26;
  }
  .car-details.K125-color .wrapper {
    border-top: 1px solid #ffbf00;
  }

  .stats-past.TPS-color .hd {
    border-bottom: 1px solid #d90000;
  }
  .stats-past.FSAC-color .hd {
    border-bottom: 1px solid #ff5c26;
  }
  .stats-past.K125-color .hd {
    border-bottom: 1px solid #ffbf00;
  }

  .driver-profile .stats-current.TPS-color li {
    border-top: 1px solid #d90000;
  }
  .driver-profile .stats-current.FSAC-color li {
     border-top: 1px solid #ff5c26;
  }
  .driver-profile .stats-current.K125-color li {
    border-top: 1px solid #ffbf00;
  }

  .driver-profile.TPS-color  .tc-data .divider {
    border-right: 1px solid #d90000;
  }
  .driver-profile.FSAC-color .tc-data .divider {
    border-right: 1px solid #ff5c26;
  }
  .driver-profile.K125-color .tc-data .divider {
    border-right: 1px solid #ffbf00;
  }
</style>

app/views/categories/race.html.erb
<div class="categories-pages">
  <div class="breadcrumbs">
    <%= link_to "Categorias", categories_path() %> / <%= link_to @category.name ,category_path(@category) %> </a> / <%= link_to "Calendario" ,category_calendar_path(@category) %> /<a class="last-it <%="#{@category.short_name}-color"%>"><%= @race.name %></a>
  </div>
  <% if @race.done == true %>
    <br>
    <%= render partial: "race_done" %>
  <% else %>
    <br>
    <%= render partial: "next_race" %>
  <% end -%>
</div>

app/views/categories/show.html.erb
<div class="categories-pages">
	<div class="breadcrumbs">
    <%= link_to "Categorias", categories_path() %> /  <a class="last-it  <%="#{@category.short_name}-color"%>" > <%= @category.name %> </a>
  </div>
	<div class="page-title <%="#{@category.short_name}-color"%>">
		<h1> <%= @category.name %> </h1>
		<%= link_to("#", class: "fb-share-btn", :"data-name" => @category.name,
		                                        :"data-caption" => "",
		                                        :"data-link" => request.original_url,
		                                        :"data-picture" => asset_url(@category.logo.url(:medium)),
		                                        :"data-description" => truncate(@category.description, length: 544) ) do %>
      <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
    <% end -%>
	</div>
	<p> <%= @category.description %> </p>
	<div class="links">
    <div class="categories-links <%="#{@category.short_name}-color"%> ">
      <%= link_to category_calendar_path(@category) do %>
        <strong>CALENDARIO</strong>
      <% end -%>
    </div>
    <div class="categories-links <%="#{@category.short_name}-color"%>">
      <%= link_to category_championships_path(@category) do %>
        <strong>CAMPEONATOS</strong>
      <% end -%>
    </div>
    <div class="categories-links <%="#{@category.short_name}-color"%>">
      <%= link_to category_pilots_path(@category) do %>
        <strong>PILOTOS</strong>
      <% end -%>
    </div>
    <div class="categories-links <%="#{@category.short_name}-color"%>">
      <%= link_to circuits_path(@category) do %>
        <strong>CIRCUITOS</strong>
      <% end -%>
    </div>
    <div class="categories-links <%="#{@category.short_name}-color"%>">
      <%= link_to category_regulation_path(@category) do %>
        <strong>REGLAMENTOS</strong>
      <% end -%>
    </div>
    <div class="categories-links <%="#{@category.short_name}-color"%>">
      <%= link_to category_gallery_path(@category) do %>
        <strong>MULTIMEDIA</strong>
      <% end -%>
    </div>
	</div>
</div>

<script type="text/javascript">
    $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });
</script>


<style type="text/css">

  .page-title.TPS-color h1 {
    color: #d90000;
  }
  .page-title.FSAC-color h1 {
    color: #ff5c26;
  }
  .page-title.K125-color h1 {
    color: #ffbf00;
  }

  .categories-links.TPS-color a {
    background-color: #d90000;
    border: 1px solid  #d90000;
  }
  .categories-links.FSAC-color a{
    background-color: #ff5c26;
    border: 1px solid  #ff5c26;
  }
  .categories-links.K125-color a{
    background-color: #ffbf00;
    border: 1px solid  #ffbf00;
  }

  .categories-links.TPS-color a:hover {
    background-color: #fff;
    border: 1px solid  #d90000;
    color: #d90000;
  }
  .categories-links.FSAC-color a:hover{
    background-color: #fff;
    border: 1px solid  #ff5c26;
    color: #ff5c26;
  }
  .categories-links.K125-color a:hover{
    background-color: #fff;
    border: 1px solid #ffbf00;
    color: #ffbf00;
  }
</style>

app/views/categories/show_albun.html.erb
<div class="categories-pages">
  <div class="breadcrumbs">
    <%= link_to "Categorias", categories_path() %> / <%= link_to @category.name ,category_path(@category) %> </a> / <%= link_to " Multimedia", category_gallery_path(@category) %> / <a class="last-it"><%= "#{@albun.name} - #{@albun.date_albun}"  %></a>
  </div>
  <div class="albun-wraper">
    <div class="tit-1">
      <h3>FOTOS</h3>
    </div>
    <div class="photo-galery-container">
      <div id="gallery" data-code="<%= @albun.code %>"></div>
    </div>
     <div class="tit-1">
      <h3>VIDEOS</h3>
    </div>
    <div class="video-galery-container">
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $("#gallery").nanoGallery({
      kind: 'flickr',
      userID: '126030921@N08',
      photoset: $('#gallery').data('code'),
      thumbnailWidth: 125,
      thumbnailHeight: 125,
      thumbnailGutterWidth: 20,
      thumbnailGutterHeight: 20,
      thumbnailLabel: { display: false }
    });
  });
</script>

app/views/categories/show_calendar.html.erb
<div class="categories-pages">
  <div class="breadcrumbs">
    <%= link_to "Categorias", categories_path() %> / <%= link_to @category.name ,category_path(@category) %> </a> / <a class="last-it  <%="#{@category.short_name}-color"%>">Calendario</a>
  </div>
  <%= link_to("#", class: "fb-share-btn regulation-F-btn", :"data-name" => "Calendario #{@category.name} #{@actual_championship.year}",
                                            :"data-caption" => "",
                                            :"data-link" => request.original_url,
                                            :"data-picture" => asset_url(@category.logo.url(:medium)),
                                            :"data-description" => "Todos las fechas y circuitos de la categoría #{@category.name}" ) do %>
      <%= image_tag 'publicarlo-en-fb.png', class: "btn-share", width: 100 %>
  <% end -%>

  <div class="calendar">
    <ul class="row circuit-list">
      <% @races.each do |race| %>
        <li class="col-sm-4 col-xs-12 link-to-circuit" style="width:32%;">
          <div class="info-circuit info-circuit2 <%= "#{@category.short_name}-color"%>">
            <div class="date"><span><%= race.date.day %></span><%= I18n.t("date.month_names")[race.date.month] %></div>
            <div class="hd <%= "#{@category.short_name}-color"%>">
              <h2><%= race.circuit.name %></h2>
              <p><%= race.circuit.location %></p>
            </div>
            <figure class="cont-circuit">
              <%= image_tag race.circuit.logo, width: 260  %>
            </figure>
            <% if race.done == true %>
              <ul class="pos">
                <li><span>1°</span><%= link_to race.race_results[0].pilot.full_name , pilot_path(@category.id, race.race_results[0].pilot_id ) %></li>
                <li><span>2°</span><%= link_to race.race_results[1].pilot.full_name , pilot_path(@category.id, race.race_results[1].pilot_id ) %></li>
                <li><span>3°</span><%= link_to race.race_results[2].pilot.full_name , pilot_path(@category.id, race.race_results[2].pilot_id ) %></li>
              </ul>
              <%= link_to "Ver más", race_path(@category.id,race.id), class: "more-txt" %>
            <% else %>
              <% if race == @actual_championship.next_race %>
                <div class="nav-race">
                  <%= link_to "El circuito", show_circuit_path(@category.id, race.circuit.id), class: "btn-small  #{@category.short_name}-color" %>
                  <% unless @actual_championship.next_race.race_previus.nil? %>
                    <%= link_to "Previa", race_path(@category.id,race.id), class: "btn-small  #{@category.short_name}-color" %>
                  <% end -%>
                </div>
                <input type="hidden" id="day_count2"   value= <%=@actual_championship.next_race.date.day    %> />
                <input type="hidden" id="month_count2" value= <%=@actual_championship.next_race.date.strftime('%B') %> />
                <input type="hidden" id="year_count2"  value= <%=@actual_championship.next_race.date.year   %> />
                <div class="countdown lite clearfix" id="countboxlite">
                  <div class="cont-num">
                    <div class="num days" id="days">0</div>
                    <span>Días</span>
                  </div>
                  <div class="cont-num">
                    <div class="num hours" id="hours">0</div>
                    <span>Horas</span>
                  </div>
                  <div class="cont-num">
                    <div class="num minutes" id="mins">0</div>
                    <span>Minutos</span>
                  </div>
                  <div class="cont-num">
                    <div class="num seconds" id="secs">0</div>
                    <span>Segundos</span>
                  </div>
                </div>
              <% else %>
                <div class="nav-race">
                  <%= link_to "circuito", show_circuit_path(@category.id, race.circuit.id), class: "btn-small #{@category.short_name}-color" %>
                </div>
              <% end -%>
            <% end -%>
          </div>
        </li>
      <% end -%>
    </ul>
    <div class="clearfix visible-lg visible-md"></div>
  </div>
</div>

<script type="text/javascript">

  $('.fb-share-btn').on( 'click', function(e) {
    e.preventDefault();
    info = $('.fb-share-btn');
    FB.ui( {
      method: 'feed',
      name: info.data("name"),
      link: info.data("link"),
      picture: info.data("picture"),
      description: info.data("description"),
      caption: info.data("caption")
    },
    function( response ) {
      if ( response !== null && typeof response.post_id !== 'undefined' ) {
        console.log( response );
        // ajax call to save response
        $.post( 'http://www.saltoautomovilclub.herokuapp.com/', { 'meta': response }, function( result ) {
          console.log( result );
        }, 'json' );
      }
    });
  });

  $("#countboxlite").countdown({
    date:  $("#day_count2").val() +" "+$("#month_count2").val()+" "+$("#year_count2").val()+" "+"09:00:00",
    format: "on"
  });

</script>


<style type="text/css">

  .btn-small {
    background-color: #e55151;
    color: #fff;
    font-family: "bebasneue_regular";
    font-size: 20px;
    padding: 5px 8px 3px;
    text-decoration: none!important;
    text-transform: none;
    transition: none 0s ease 0s ;
  }

  .hd.TPS-color h2 {
    color: #d90000;
  }
  .hd.FSAC-color h2 {
    color: #ff5c26;
  }
  .hd.K125-color h2 {
    color: #ffbf00;
  }

  .info-circuit.TPS-color:hover {
    border: 1px solid #d90000;
  }
  .info-circuit.FSAC-color:hover {
    border: 1px solid #ff5c26;
  }
  .info-circuit.K125-color:hover {
    border: 1px solid #ffbf00;
  }

  .calendar .info-circuit.TPS-color .pos > li > span {
    color: #d90000;
  }
  .calendar .info-circuit.FSAC-color .pos > li > span {
    color: #ff5c26;
  }
  .calendar .info-circuit.K125-color .pos > li > span {
    color: #ffbf00;
  }

  .calendar .info-circuit.TPS-color .more-txt {
    background-color: #d90000;
    color:#fff;
  }
  .calendar .info-circuit.FSAC-color .more-txt {
    background-color: #ff5c26;
    color:#fff;
  }
  .calendar .info-circuit.K125-color .more-txt {
    background-color: #ffbf00;
    color:#fff;
  }

  .calendar .info-circuit.TPS-color .btn-small {
    background-color: #d90000;
    color:#fff;
  }
  .calendar .info-circuit.FSAC-color .btn-small {
    background-color: #ff5c26;
    color:#fff;
  }
  .calendar .info-circuit.K125-color .btn-small {
    background-color: #ffbf00;
    color:#fff;
  }

  .calendar .info-circuit.TPS-color .more-txt:hover {
    background-color:#555;
  }
  .calendar .info-circuit.FSAC-color .more-txt:hover {
    background-color:#555;
  }
  .calendar .info-circuit.K125-color .more-txt:hover {
    background-color:#555;
  }

  .calendar .info-circuit.TPS-color .btn-small:hover {
    background-color:#555;
  }
  .calendar .info-circuit.FSAC-color .btn-small:hover {
    background-color:#555;
  }
  .calendar .info-circuit.K125-color .btn-small:hover {
    background-color:#555;
  }

</style>